//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEP2020.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Role { get; set; }
        public string Check_active { get; set; }
        public string Status { get; set; }
        public string ms_id { get; set; }
        public int Falcuty_id { get; set; }
        public string Email { get; set; }
    
        public virtual Faculty Faculty { get; set; }
    }
}
